name: Another workflow
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Get node version
        id: node-version
        run: |
          echo "::set-output name=version::$(node --version)"
      - name: Setup yarn cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: v1-${{ steps.node-version.outputs.version }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-${{ steps.node-version.outputs.version }}-node-
      - name: yarn install
        run: |
          yarn install
      - name: yarn test
        run: |
          yarn test
      - name: yarn type-check
        run: |
          yarn type-check
      - name: yarn prettier
        run: |
          yarn prettier
      - name: Commit report
        run: |
          if [ -n "$(git status -s)" ]; then
            echo "Changes detected";
            git fetch --depth=1
            git checkout "${GITHUB_REF#refs/heads/}}"
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git commit -am "Automated report" \
            --author '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
            git push --set-upstream origin "HEAD:${GITHUB_REF#refs/heads/}}"
          else
            echo "Working tree clean. Nothing to commit.";
          fi
