name: Another workflow
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Get node version
        id: node-version
        run: |
          echo "::set-output name=version::$(node --version)"
      - name: Setup yarn cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: v1-${{ steps.node-version.outputs.version }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-${{ steps.node-version.outputs.version }}-node-
      - name: yarn install
        with:
          cmd: install
      - name: yarn test
        with:
          cmd: test
      - name: yarn type-check
        with:
          cmd: type-check
      - name: yarn prettier
        with:
          cmd: prettier
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Regenerate api types based off of schema update'