name: Clean commit
on:
  push:
    branches:
      - "main"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    # if: "contains(github.event.head_commit.message, '[skip]')"
    steps:
      - uses: actions/checkout@v2
      - name: Clean new commit to main
        run: |
            echo "Changes detected - ${{ github.event.head_commit.message }}"
            SUB='[skip]'
            for commit in $(git log --oneline $branch ^origin/main)
            do
                echo $commit
            done
