name: Clean commit
on:
  push:
    branches:
      - "main"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    # if: "contains(github.event.head_commit.message, '[skip]')"
    steps:
      - uses: actions/checkout@v2
      - name: Clean new commit to main
        run: |
            echo "Changes detected - ${{ github.event.head_commit.message }}"
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git commit -am "Automated report" \
            --author '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
            git push