name: GitHub Actions Demo
on:
  push:
    branches:
      - test
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: type-check
      - run: echo "🍏 This job's status is ${{ job.status }}."