name: GitHub Actions Demo
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: yarn test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
      - name: yarn type-check
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: type-check
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          message: 'Regenerate api types based off of schema update'
      - run: echo "🍏 This job's status is ${{ job.status }}."