name: Push repo test
on:
  push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Create pull request
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUSH_REPO_TOKEN }}
        run: |
          CLONE_DIR=$(mktemp -d)
          TARGET_BRANCH="master"
          USER_NAME="GitHub Actions"
          DESTINATION_REPOSITORY_NAME="NickLewry/beer-utiful"

          echo "[+] Cloning destination git repository $DESTINATION_REPOSITORY_NAME"

          git config --global user.name $USER_NAME
          git config --global user.email 'actions@github.com'

          git clone --single-branch --branch "$TARGET_BRANCH" "https://$USER_NAME:$API_TOKEN_GITHUB@$GITHUB_SERVER$DESTINATION_REPOSITORY_NAME.git" "$CLONE_DIR"

          ls -la "$CLONE_DIR"


