name: Push repo test
on:
  push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Create pull request
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUSH_REPO_TOKEN }}
        run: |
          CLONE_DIR=$(mktemp -d)
          TARGET_BRANCH="master"
          USER_NAME="GitHub Actions"
          TARGET_DIRECTORY="bru/random"
          DESTINATION_REPOSITORY_NAME="beer-utiful"

          echo "[+] Cloning destination git repository $DESTINATION_REPOSITORY_NAME"

          git config --global user.name $USER_NAME
          git config --global user.email 'actions@github.com'

          git clone --single-branch --branch "$TARGET_BRANCH" "https://github.com/NickLewry/beer-utiful.git" "$CLONE_DIR"

          ls -la "$CLONE_DIR"

          TEMP_DIR=$(mktemp -d)

          mv "$CLONE_DIR/.git" "$TEMP_DIR/.git"

          if [ -n "$TARGET_DIRECTORY" ]
          then

            echo "[+] Checking if $TARGET_DIRECTORY exist in git repo $DESTINATION_REPOSITORY_NAME"

            # Remove contents of target directory and create a new empty one
            if [ -d "$CLONE_DIR/$TARGET_DIRECTORY/" ]
            then
              echo "[+] Deleting files from $TARGET_DIRECTORY in git repo $DESTINATION_REPOSITORY_NAME"
              rm -R "$CLONE_DIR/$TARGET_DIRECTORY/"
            fi
            echo "[+] Creating $TARGET_DIRECTORY if doesnt already exist"

            mkdir -p "$CLONE_DIR/$TARGET_DIRECTORY"

            echo "[+] Listing Current Directory Location"
            ls -al

            echo "[+] Listing root Location"
            ls -al /
          fi


